#!/usr/bin/env bash
#  command-reqs -*- mode: sh -*-
set -euo pipefail

echo "Creating tex requirements file"
if [[ $# -eq 0 ]]; then
    tlmgr info --only-installed --data name > ./tex.reqs
else
    tlmgr info --only-installed --data name > $1
fi
